# Prepration

In [20]:
import pandas as pd
data = pd.read_excel('../Materials/input_node.xlsx')
dist_and_time = pd.read_csv('../Materials/input_distance-time.txt')

In [21]:
data.head()

,ID,type,lng,lat,pack_total_weight,pack_total_volume,first_receive_tm,last_receive_tm
0,0,1,116.571614,39.792844,-,-,08:00:00,1900-01-01 00:00:00
1,1,2,116.242043,40.072630,0.2076,0.3666,09:00:00,12:00:00
2,2,2,116.403595,39.872945,0.05863,0.1687,13:30:00,14:00:00
3,3,2,116.186289,40.016361,0.03645,0.0745,13:00:00,15:00:00
4,4,2,116.508011,39.826296,0.02595,0.0542,09:00:00,10:00:00

In [22]:
dist_and_time.head()

   ID  from_node  to_node  distance  spend_tm
0   0          0        1     63536        77
1   1          0        2     27489        33
2   2          0        3     62041        75
3   3          0        4     13365        17
4   4          0        5     45570        55

In [23]:
# Set parameters
nbCustomer = 50
nbCars = 10

In [24]:
# get the distance from i to j
def getDist (fromNode,toNode):
    dist = dist_and_time[(dist_and_time.from_node == fromNode) & (dist_and_time.to_node == toNode)]
    return int(dist.distance)

# get the traval time from i to j
def getTime (fromNode,toNode):
    dist = dist_and_time[(dist_and_time.from_node == fromNode) & (dist_and_time.to_node == toNode)]
    return int(dist.spend_tm)

# get weight of node i
def getWeit (i):
    if i in range(1,1001):             # check if i is allowed
        row = data[data.ID == i]
        return float(row.pack_total_weight)
    else:                            # if i is not allowed     
        print('input of weight is illegal')
        
# get volume of node i
def getVolu (i):
    if i in range(1,1001):
        row = data[data.ID == i]
        return float(row.pack_total_volume)
    else: 
        print('input of volume is illegal')

# Get the best order of routes

In [25]:
# Pick up customers in the order
custID = list(range(1,nbCustomer + 1))

In [26]:
# Given the customer ID
#custID= [185,888,423,360,660,662,137,322,631,689,559,550,582,606,943,901,121,763,972,303,247
#        ,17,140,101,255,851,645,977,601,810,406,400,182,484,276,359,947,215,616,221,299,833
#        ,184,604,443,283,51,109,331,842]

In [27]:
# Initialization
routes = [0]
starNode = 0
toNode = 1

for i in range(1,nbCustomer + 1):
    Dist = getDist(starNode,custID[0])
    print('\nattemp',i,': from',starNode,'to ?')
    
    for j in custID:
        if (j != starNode):
            if getDist(starNode,j) <= Dist:
                toNode = j 
                Dist = getDist(starNode,j)
    print('the nearest node of',starNode,'is',toNode,',the distance is',Dist)
    
    custID.remove(toNode)
    routes.append(toNode)
    print('routes are',routes)
    starNode = toNode

print("\n\nCaculation completed")
routes.append(0)
print('The final routes are:\n',routes)

attemp 1 : from 0 to ?
the nearest node of 0 is 37 ,the distance is 12285
routes are [0, 37]

attemp 2 : from 37 to ?
the nearest node of 37 is 14 ,the distance is 11363
routes are [0, 37, 14]

attemp 3 : from 14 to ?
the nearest node of 14 is 43 ,the distance is 18850
routes are [0, 37, 14, 43]

attemp 4 : from 43 to ?
the nearest node of 43 is 36 ,the distance is 9581
routes are [0, 37, 14, 43, 36]

attemp 5 : from 36 to ?
the nearest node of 36 is 41 ,the distance is 11785
routes are [0, 37, 14, 43, 36, 41]

attemp 6 : from 41 to ?
the nearest node of 41 is 33 ,the distance is 6552
routes are [0, 37, 14, 43, 36, 41, 33]

attemp 7 : from 33 to ?
the nearest node of 33 is 10 ,the distance is 11284
routes are [0, 37, 14, 43, 36, 41, 33, 10]

attemp 8 : from 10 to ?
the nearest node of 10 is 32 ,the distance is 9058
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32]

attemp 9 : from 32 to ?
the nearest node of 32 is 6 ,the distance is 7188
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6]

attemp 10 : from 6 to ?
the nearest node of 6 is 46 ,the distance is 10131
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46]

attemp 11 : from 46 to ?
the nearest node of 46 is 49 ,the distance is 11146
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49]

attemp 12 : from 49 to ?
the nearest node of 49 is 16 ,the distance is 14190
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16]

attemp 13 : from 16 to ?
the nearest node of 16 is 1 ,the distance is 12722
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1]

attemp 14 : from 1 to ?
the nearest node of 1 is 50 ,the distance is 12141
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50]

attemp 15 : from 50 to ?
the nearest node of 50 is 19 ,the distance is 6708
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19]

attemp 16 : from 19 to ?
the nearest node of 19 is 12 ,the distance is 10693
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12]

attemp 17 : from 12 to ?
the nearest node of 12 is 39 ,the distance is 7474
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39]

attemp 18 : from 39 to ?
the nearest node of 39 is 26 ,the distance is 9792
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26]

attemp 19 : from 26 to ?
the nearest node of 26 is 20 ,the distance is 16092
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20]

attemp 20 : from 20 to ?
the nearest node of 20 is 35 ,the distance is 14697
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35]

attemp 21 : from 35 to ?
the nearest node of 35 is 42 ,the distance is 10595
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42]

attemp 22 : from 42 to ?
the nearest node of 42 is 31 ,the distance is 12078
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31]

attemp 23 : from 31 to ?
the nearest node of 31 is 25 ,the distance is 8701
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25]

attemp 24 : from 25 to ?
the nearest node of 25 is 30 ,the distance is 10874
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30]

attemp 25 : from 30 to ?
the nearest node of 30 is 47 ,the distance is 17662
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47]

attemp 26 : from 47 to ?
the nearest node of 47 is 44 ,the distance is 11245
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44]

attemp 27 : from 44 to ?
the nearest node of 44 is 23 ,the distance is 10506
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23]

attemp 28 : from 23 to ?
the nearest node of 23 is 4 ,the distance is 36694
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4]

attemp 29 : from 4 to ?
the nearest node of 4 is 8 ,the distance is 4553
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8]

attemp 30 : from 8 to ?
the nearest node of 8 is 7 ,the distance is 11136
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7]

attemp 31 : from 7 to ?
the nearest node of 7 is 29 ,the distance is 9060
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29]

attemp 32 : from 29 to ?
the nearest node of 29 is 45 ,the distance is 5047
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45]

attemp 33 : from 45 to ?
the nearest node of 45 is 2 ,the distance is 6030
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2]

attemp 34 : from 2 to ?
the nearest node of 2 is 40 ,the distance is 6394
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40]

attemp 35 : from 40 to ?
the nearest node of 40 is 11 ,the distance is 7873
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11]

attemp 36 : from 11 to ?
the nearest node of 11 is 27 ,the distance is 5901
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27]

attemp 37 : from 27 to ?
the nearest node of 27 is 18 ,the distance is 7645
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18]

attemp 38 : from 18 to ?
the nearest node of 18 is 28 ,the distance is 8111
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28]

attemp 39 : from 28 to ?
the nearest node of 28 is 24 ,the distance is 10289
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24]

attemp 40 : from 24 to ?
the nearest node of 24 is 9 ,the distance is 15920
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9]

attemp 41 : from 9 to ?
the nearest node of 9 is 17 ,the distance is 9945
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17]

attemp 42 : from 17 to ?
the nearest node of 17 is 38 ,the distance is 14183
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38]

attemp 43 : from 38 to ?
the nearest node of 38 is 15 ,the distance is 15755
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15]

attemp 44 : from 15 to ?
the nearest node of 15 is 34 ,the distance is 10932
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34]

attemp 45 : from 34 to ?
the nearest node of 34 is 22 ,the distance is 16839
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22]

attemp 46 : from 22 to ?
the nearest node of 22 is 5 ,the distance is 5750
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5]

attemp 47 : from 5 to ?

the nearest node of 5 is 21 ,the distance is 21379
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21]

attemp 48 : from 21 to ?
the nearest node of 21 is 3 ,the distance is 12939
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3]

attemp 49 : from 3 to ?
the nearest node of 3 is 13 ,the distance is 9933
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3, 13]

attemp 50 : from 13 to ?
the nearest node of 13 is 48 ,the distance is 7639
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3, 13, 48]


Caculation completed
The final routes are:
 [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3, 13, 48, 0]

# Cut the routes

In [28]:
# Remove distribution center O to get a set of customers.
if 0 in routes:  
    routes.remove(0)
    routes.remove(0)
    print("Removal completed!")
else:
    print("There is no distribution in this set")

Removal completed!

In [29]:
print(routes)

[37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3, 13, 48]

In [30]:
# The capacity of truck
max_weit = 2.5
max_volu = 16
max_driv = 200000
max_time = 720

In [31]:
# Initialization
fromNode = 0
weight = 0
volume = 0
distance = 0
time = 0
routePlan = [0]
truck = 1
travelCost = 0
timeExceed = 0

for nextNode in routes:
    # If next customer could fit.
    if ((weight+getWeit(nextNode)<=max_weit)&(volume+getVolu(nextNode)<=max_volu)&(distance+getDist(fromNode,nextNode)+getDist(nextNode,0)<=max_driv)&(time<=max_time+getTime(fromNode,nextNode)+getTime(nextNode,0))):
        routePlan.append(nextNode)
        distance = distance + getDist(fromNode,nextNode)
        time = time + getTime(fromNode,nextNode)
        weight = weight + getWeit(nextNode)
        volume = volume + getVolu(nextNode)
        fromNode = nextNode  
    
    # If next customer doesn't fit, let truck go back.
    else:
        routePlan.append(0)
        time = time + getTime(fromNode,0)
        distance = distance + getDist(fromNode,0)
        travelCost = travelCost + distance * 14 /1000
        # Print the route of this truck.
        print("The route of truck",truck,"is",routePlan)
        print('Total weight is',weight)
        print('Total volume is',volume)
        print('Total traval time is',time)
        print('Total traval distance is',distance)
        print('\n')
        
        # Reset all of the capacity and make assignment for next truck.
        truck = truck + 1
        weight = 0
        volume = 0
        distance = 0
        time = 0
        routePlan = [0]
        fromNode = 0
        
        # If this "nextNode" could fit in a new truck?
        if ((weight<=max_weit)&(volume<=max_volu)&(distance+getDist(fromNode,nextNode)+getDist(nextNode,0)<=max_driv)&(time<=max_time+getTime(fromNode,nextNode)+getTime(nextNode,0))): 
            distance = distance + getDist(fromNode,nextNode)
            time = time + getTime(fromNode,nextNode)
            weight = weight + getWeit(nextNode)
            volume = volume + getVolu(nextNode)
            routePlan.append(nextNode)
            fromNode = nextNode
            
        else:
            print("Oh no!")
            break

# The last loop is completed and let this truck go home.
routePlan.append(0)
time = time + getTime(fromNode,0)
distance = distance + getDist(fromNode,0)

# caculate the cost
travelCost = travelCost + distance * 14 /1000
fixCost = truck * 300

# print the result
print("The route of truck",truck,"is",routePlan)
print('Total weight is',weight)
print('Total volume is',volume)
print('Total traval time is',time)
print('Total traval distance is',distance)
print('\n')
print("Completed!")

The route of truck 1 is [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 0]
Total weight is 1.686252
Total volume is 6.6091999999999995
Total traval time is 240
Total traval distance is 194390


The route of truck 2 is [0, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 0]
Total weight is 0.53201
Total volume is 1.1965999999999999
Total traval time is 243
Total traval distance is 198107


The route of truck 3 is [0, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 0]
Total weight is 0.9317500000000002
Total volume is 2.8777
Total traval time is 240
Total traval distance is 193581


The route of truck 4 is [0, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 0]
Total weight is 1.522232
Total volume is 7.3968
Total traval time is 243
Total traval distance is 196080


The route of truck 5 is [0, 21, 3, 13, 48, 0]
Total weight is 0.786755
Total volume is 1.4193999999999998
Total traval time is 196
Total traval distance is 161388


Completed!

# Caculate the total cost

In [32]:
totalCost = fixCost + travelCost + timeExceed
totalCost

14709.644

# Write result into CSV file

In [33]:
dic = {"John": "john@example.com", "Mary": "mary@example.com"} #dictionary

download_dir = "Routes50.csv" #where you want the file to be downloaded to 

csv = open(download_dir, "w") 
#"w" indicates that you're writing strings to the file

columnTitleRow = "TruckID, Routes\n"
csv.write(columnTitleRow)

for key in dic.keys():
    name = key
    email = dic[key]
    row = name + "," + email + "\n"
    csv.write(row)