# Prepration

In [1]:
import pandas as pd
data = pd.read_excel('../Materials/input_node.xlsx')
dist_and_time = pd.read_csv('../Materials/input_distance-time.txt')

In [2]:
data.head()

,ID,type,lng,lat,pack_total_weight,pack_total_volume,first_receive_tm,last_receive_tm
0,0,1,116.571614,39.792844,-,-,08:00:00,1900-01-01 00:00:00
1,1,2,116.242043,40.072630,0.2076,0.3666,09:00:00,12:00:00
2,2,2,116.403595,39.872945,0.05863,0.1687,13:30:00,14:00:00
3,3,2,116.186289,40.016361,0.03645,0.0745,13:00:00,15:00:00
4,4,2,116.508011,39.826296,0.02595,0.0542,09:00:00,10:00:00

In [3]:
dist_and_time.head()

   ID  from_node  to_node  distance  spend_tm
0   0          0        1     63536        77
1   1          0        2     27489        33
2   2          0        3     62041        75
3   3          0        4     13365        17
4   4          0        5     45570        55

In [4]:
# initialization
nbCus = 50
nbCars = 10

In [5]:
# get the distance from i to j
def getDist (fromNode,toNode):
    dist = dist_and_time[(dist_and_time.from_node == fromNode) & (dist_and_time.to_node == toNode)]
    return int(dist.distance)

# get the traval time from i to j
def getTime (fromNode,toNode):
    dist = dist_and_time[(dist_and_time.from_node == fromNode) & (dist_and_time.to_node == toNode)]
    return dist.spend_tm

# get weight of node i
def getWeit (i):
    # check if i is allowed
    if i in range(1,51):
        row = data[data.ID == 1]
        return row.pack_total_weight
    # if i is not allowed
    else: 
        print('input is illegal')
        
# get volume of node i
def getVolu (i):
    # check if i is allowed
    if i in range(1,51):
        row = data[data.ID == 1]
        return row.pack_total_volume
    # if i is not allowed
    else: 
        print('input is illegal')

# Get the routes

In [68]:
# Initialization
routes=[0]
custID = list(range(1,51))
starNode = 0
toNode = 1

In [69]:
for i in range(1,51):
    Dist = getDist(starNode,custID[0])
    print('\n\ntemp',i,': from',starNode,'to ?')
    
    for j in custID:
        if (j != starNode):
            if getDist(starNode,j) <= Dist:
                toNode = j 
                Dist = getDist(starNode,j)
    print('the nearest node of',starNode,'is',toNode,',the distance is',Dist)
    
    custID.remove(toNode)
    routes.append(toNode)
    print('routes are',routes)
    starNode = toNode

print("\n\nCaculation completed")
routes.append(0)
print('The final routes are:\n',routes)

temp 1 : from 0 to ?
the nearest node of 0 is 37 ,the distance is 12285
routes are [0, 37]


temp 2 : from 37 to ?
the nearest node of 37 is 14 ,the distance is 11363
routes are [0, 37, 14]


temp 3 : from 14 to ?
the nearest node of 14 is 43 ,the distance is 18850
routes are [0, 37, 14, 43]


temp 4 : from 43 to ?
the nearest node of 43 is 36 ,the distance is 9581
routes are [0, 37, 14, 43, 36]


temp 5 : from 36 to ?
the nearest node of 36 is 41 ,the distance is 11785
routes are [0, 37, 14, 43, 36, 41]


temp 6 : from 41 to ?
the nearest node of 41 is 33 ,the distance is 6552
routes are [0, 37, 14, 43, 36, 41, 33]


temp 7 : from 33 to ?
the nearest node of 33 is 10 ,the distance is 11284
routes are [0, 37, 14, 43, 36, 41, 33, 10]


temp 8 : from 10 to ?
the nearest node of 10 is 32 ,the distance is 9058
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32]


temp 9 : from 32 to ?
the nearest node of 32 is 6 ,the distance is 7188
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6]


temp 10 : from 6 to ?
the nearest node of 6 is 46 ,the distance is 10131
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46]


temp 11 : from 46 to ?
the nearest node of 46 is 49 ,the distance is 11146
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49]


temp 12 : from 49 to ?
the nearest node of 49 is 16 ,the distance is 14190
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16]


temp 13 : from 16 to ?
the nearest node of 16 is 1 ,the distance is 12722
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1]


temp 14 : from 1 to ?
the nearest node of 1 is 50 ,the distance is 12141
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50]


temp 15 : from 50 to ?
the nearest node of 50 is 19 ,the distance is 6708
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19]


temp 16 : from 19 to ?
the nearest node of 19 is 12 ,the distance is 10693
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12]


temp 17 : from 12 to ?
the nearest node of 12 is 39 ,the distance is 7474
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39]


temp 18 : from 39 to ?
the nearest node of 39 is 26 ,the distance is 9792
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26]


temp 19 : from 26 to ?
the nearest node of 26 is 20 ,the distance is 16092
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20]


temp 20 : from 20 to ?
the nearest node of 20 is 35 ,the distance is 14697
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35]


temp 21 : from 35 to ?
the nearest node of 35 is 42 ,the distance is 10595
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42]


temp 22 : from 42 to ?
the nearest node of 42 is 31 ,the distance is 12078
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31]


temp 23 : from 31 to ?
the nearest node of 31 is 25 ,the distance is 8701
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25]


temp 24 : from 25 to ?
the nearest node of 25 is 30 ,the distance is 10874
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30]


temp 25 : from 30 to ?
the nearest node of 30 is 47 ,the distance is 17662
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47]


temp 26 : from 47 to ?
the nearest node of 47 is 44 ,the distance is 11245
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44]


temp 27 : from 44 to ?
the nearest node of 44 is 23 ,the distance is 10506
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23]


temp 28 : from 23 to ?
the nearest node of 23 is 4 ,the distance is 36694
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4]


temp 29 : from 4 to ?
the nearest node of 4 is 8 ,the distance is 4553
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8]


temp 30 : from 8 to ?
the nearest node of 8 is 7 ,the distance is 11136
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7]


temp 31 : from 7 to ?
the nearest node of 7 is 29 ,the distance is 9060
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29]


temp 32 : from 29 to ?
the nearest node of 29 is 45 ,the distance is 5047
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45]


temp 33 : from 45 to ?
the nearest node of 45 is 2 ,the distance is 6030
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2]


temp 34 : from 2 to ?
the nearest node of 2 is 40 ,the distance is 6394
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40]


temp 35 : from 40 to ?
the nearest node of 40 is 11 ,the distance is 7873
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11]


temp 36 : from 11 to ?
the nearest node of 11 is 27 ,the distance is 5901
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27]


temp 37 : from 27 to ?
the nearest node of 27 is 18 ,the distance is 7645
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18]


temp 38 : from 18 to ?
the nearest node of 18 is 28 ,the distance is 8111
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28]


temp 39 : from 28 to ?
the nearest node of 28 is 24 ,the distance is 10289
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24]


temp 40 : from 24 to ?
the nearest node of 24 is 9 ,the distance is 15920
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9]


temp 41 : from 9 to ?
the nearest node of 9 is 17 ,the distance is 9945
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17]


temp 42 : from 17 to ?
the nearest node of 17 is 38 ,the distance is 14183
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38]


temp 43 : from 38 to ?
the nearest node of 38 is 15 ,the distance is 15755
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15]


temp 44 : from 15 to ?
the nearest node of 15 is 34 ,the distance is 10932
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34]


temp 45 : from 34 to ?
the nearest node of 34 is 22 ,the distance is 16839
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22]


temp 46 : from 22 to ?
the nearest node of 22 is 5 ,the distance is 5750
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5]

temp 47 : from 5 to ?
the nearest node of 5 is 21 ,the distance is 21379
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21]


temp 48 : from 21 to ?
the nearest node of 21 is 3 ,the distance is 12939
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3]


temp 49 : from 3 to ?
the nearest node of 3 is 13 ,the distance is 9933
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3, 13]


temp 50 : from 13 to ?
the nearest node of 13 is 48 ,the distance is 7639
routes are [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3, 13, 48]


Caculation completed
The final routes are:
 [0, 37, 14, 43, 36, 41, 33, 10, 32, 6, 46, 49, 16, 1, 50, 19, 12, 39, 26, 20, 35, 42, 31, 25, 30, 47, 44, 23, 4, 8, 7, 29, 45, 2, 40, 11, 27, 18, 28, 24, 9, 17, 38, 15, 34, 22, 5, 21, 3, 13, 48, 0]

# Cut the routes

In [75]:
rout = routes
rout.remove(0)

ValueError: list.remove(x): x not in list

In [66]:
# weight and volume constraints

weight = 0
volume = 0
for cust in routes:
        weight = weight + getWeit(cust)
        volume = volume + getVolu(cust)